jdbc.datasource.driverClassName=org.postgresql.Driver
jdbc.datasource.url=${DATASOURCE_URL}

# TODO: Add additional database users for different user levels.
jdbc.datasource.superuser.username=${POSTGRES_USER}
jdbc.datasource.superuser.password=${POSTGRES_PASSWORD}

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true

# TODO: Make the value profile-dependent, i.e. `create-drop` for `dev`
#       profile and `update` for `release` profile.
hibernate.hbm2ddl.auto=create-drop
